# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KCTS(object):
    def setupUi(self, KCTS):
        KCTS.setObjectName("KCTS")
        KCTS.resize(614, 439)
        self.Window = QtWidgets.QWidget(KCTS)
        self.Window.setObjectName("Window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Window)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Menu = QtWidgets.QWidget(self.Window)
        self.Menu.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Menu.setStyleSheet("background-color: rgb(125, 125, 125);")
        self.Menu.setObjectName("Menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(120, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.system_label = QtWidgets.QLabel(self.Menu)
        self.system_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.system_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.system_label.setStyleSheet("font: 20pt \"幼圆\";")
        self.system_label.setAlignment(QtCore.Qt.AlignCenter)
        self.system_label.setObjectName("system_label")
        self.horizontalLayout.addWidget(self.system_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.Menu)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.Menu)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.Menu)
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.Menu)
        self.Body = QtWidgets.QWidget(self.Window)
        self.Body.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.Body.setObjectName("Body")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Body)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.navigation_list = QtWidgets.QListWidget(self.Body)
        self.navigation_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.navigation_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.navigation_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.navigation_list.setItemAlignment(QtCore.Qt.AlignCenter)
        self.navigation_list.setObjectName("navigation_list")
        self.horizontalLayout_2.addWidget(self.navigation_list)
        self.sub_interface_stacked = QtWidgets.QStackedWidget(self.Body)
        self.sub_interface_stacked.setObjectName("sub_interface_stacked")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.sub_interface_stacked.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.sub_interface_stacked.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.sub_interface_stacked)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 15)
        self.verticalLayout.addWidget(self.Body)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        KCTS.setCentralWidget(self.Window)

        self.retranslateUi(KCTS)
        QtCore.QMetaObject.connectSlotsByName(KCTS)

    def retranslateUi(self, KCTS):
        _translate = QtCore.QCoreApplication.translate
        KCTS.setWindowTitle(_translate("KCTS", "KCTS"))
        self.system_label.setText(_translate("KCTS", "KCTS"))
        self.pushButton.setText(_translate("KCTS", "选择项目"))
        self.pushButton_2.setText(_translate("KCTS", "生成报告"))
        self.pushButton_3.setText(_translate("KCTS", "……"))
