# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(562, 474)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Window)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.num_lineEdit = QtWidgets.QLineEdit(Window)
        self.num_lineEdit.setObjectName("num_lineEdit")
        self.verticalLayout_5.addWidget(self.num_lineEdit)
        self.ip_lineEdit = QtWidgets.QLineEdit(Window)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.verticalLayout_5.addWidget(self.ip_lineEdit)
        self.targetPort_label = QtWidgets.QLabel(Window)
        self.targetPort_label.setObjectName("targetPort_label")
        self.verticalLayout_5.addWidget(self.targetPort_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(Window)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.targetIp_label = QtWidgets.QLabel(Window)
        self.targetIp_label.setObjectName("targetIp_label")
        self.verticalLayout_5.addWidget(self.targetIp_label)
        self.port_lineEdit = QtWidgets.QLineEdit(Window)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.verticalLayout_5.addWidget(self.port_lineEdit)
        self.connect_pushButton = QtWidgets.QPushButton(Window)
        self.connect_pushButton.setStyleSheet("background:rgb(255, 255, 127)")
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.verticalLayout_5.addWidget(self.connect_pushButton)
        self.openFile_pushButton = QtWidgets.QPushButton(Window)
        self.openFile_pushButton.setObjectName("openFile_pushButton")
        self.verticalLayout_5.addWidget(self.openFile_pushButton)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "OU Simulator"))
        self.num_lineEdit.setPlaceholderText(_translate("Window", "多少对按键"))
        self.targetPort_label.setText(_translate("Window", "Target_Port"))
        self.targetIp_label.setText(_translate("Window", "Target_IP"))
        self.connect_pushButton.setText(_translate("Window", "连接"))
        self.openFile_pushButton.setText(_translate("Window", "打开文件"))
