# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(896, 604)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Window)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        # self.central_widget = QtWidgets.QWidget()
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.num_lineEdit = QtWidgets.QLineEdit(Window)
        self.num_lineEdit.setObjectName("num_lineEdit")
        self.verticalLayout_4.addWidget(self.num_lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.pushButton = QtWidgets.QPushButton(Window)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.e_stop_lineEdit = QtWidgets.QLineEdit(Window)
        self.e_stop_lineEdit.setText("")
        self.e_stop_lineEdit.setObjectName("e_stop_lineEdit")
        self.gridLayout_2.addWidget(self.e_stop_lineEdit, 0, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.e_stop_lock_checkbox = QtWidgets.QCheckBox(Window)
        self.e_stop_lock_checkbox.setObjectName("e_stop_lock_checkbox")
        self.verticalLayout.addWidget(self.e_stop_lock_checkbox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.e_stop_button = QtWidgets.QPushButton(Window)
        self.e_stop_button.setEnabled(True)
        self.e_stop_button.setObjectName("e_stop_button")
        self.gridLayout_2.addWidget(self.e_stop_button, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.targetIp_label = QtWidgets.QLabel(Window)
        self.targetIp_label.setObjectName("targetIp_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.targetIp_label)
        self.ip_lineEdit = QtWidgets.QLineEdit(Window)
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip_lineEdit)
        self.targetPort_label = QtWidgets.QLabel(Window)
        self.targetPort_label.setObjectName("targetPort_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.targetPort_label)
        self.port_lineEdit = QtWidgets.QLineEdit(Window)
        self.port_lineEdit.setObjectName("port_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_lineEdit)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openFile_pushButton = QtWidgets.QPushButton(Window)
        self.openFile_pushButton.setObjectName("openFile_pushButton")
        self.verticalLayout_2.addWidget(self.openFile_pushButton)
        self.connect_pushButton = QtWidgets.QPushButton(Window)
        self.connect_pushButton.setStyleSheet("background:rgb(255, 255, 127)")
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.verticalLayout_2.addWidget(self.connect_pushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        # self.setCentralWidget(self.central_widget)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Form"))
        self.num_lineEdit.setPlaceholderText(_translate("Window", "多少对按键"))
        self.pushButton.setText(_translate("Window", "PushButton"))
        self.e_stop_lock_checkbox.setText(_translate("Window", "自锁"))
        self.e_stop_button.setText(_translate("Window", "急停"))
        self.targetIp_label.setText(_translate("Window", "Target_IP"))
        self.targetPort_label.setText(_translate("Window", "Target_Port"))
        self.openFile_pushButton.setText(_translate("Window", "打开文件"))
        self.connect_pushButton.setText(_translate("Window", "连接"))
